import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import { shadcn } from "@clerk/ui/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className='min-h-full flex flex-col items-center'>
        <ClerkProvider appearance={{ theme: shadcn }}>
          <header className='flex justify-between items-center py-4 gap-4 h-16 w-6xl'>
            <Link href='/' className='text-lg font-semibold text-foreground'>
              Link Shortener
            </Link>
            <div className='flex items-center gap-4'>
              <Show when='signed-out'>
                <Button asChild variant='outline'>
                  <SignInButton mode='modal' />
                </Button>
                <Button asChild>
                  <SignUpButton mode='modal' />
                </Button>
              </Show>
              <UserButton />
            </div>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
